/* WorkAbroad Hub — destinations & trades (3 languages) */
window.WAH = {
  agency: {
    name: 'WorkAbroad Hub',
    tagline: 'CONNECTING YOU TO GLOBAL OPPORTUNITIES',
    city: { en: 'Kolkata, West Bengal', hi: 'कोलकाता, पश्चिम बंगाल', bn: 'কলকাতা, পশ্চিমবঙ্গ' },
    phone: '+91 70638 24707',
    whatsapp: '917063824707',
    email: 'workabroadhub1@gmail.com',
    fee: 500,
    payLink: '#'          // SuperProfile ₹500 link goes here
  },

  /* ---------- destinations ---------- */
  countries: [
    { id:'ae', fl:'🇦🇪', code:'DXB',
      n:{ en:'Dubai / UAE',    hi:'दुबई / UAE',     bn:'দুবাই / UAE' },
      d:{ en:'Highest demand', hi:'सबसे ज़्यादा डिमांड', bn:'সবচেয়ে বেশি চাহিদা' } },
    { id:'sa', fl:'🇸🇦', code:'RUH',
      n:{ en:'Saudi Arabia',   hi:'सऊदी अरब',        bn:'সৌদি আরব' },
      d:{ en:'Construction & driving', hi:'कंस्ट्रक्शन और ड्राइविंग', bn:'কনস্ট্রাকশন ও ড্রাইভিং' } },
    { id:'qa', fl:'🇶🇦', code:'DOH',
      n:{ en:'Qatar',          hi:'क़तर',            bn:'কাতার' },
      d:{ en:'Hospitality & factory', hi:'होटल और फैक्ट्री', bn:'হোটেল ও ফ্যাক্টরি' } },
    { id:'kw', fl:'🇰🇼', code:'KWI',
      n:{ en:'Kuwait',         hi:'कुवैत',           bn:'কুয়েত' },
      d:{ en:'Cleaning & helper', hi:'क्लीनिंग और हेल्पर', bn:'ক্লিনিং ও হেল্পার' } },
    { id:'om', fl:'🇴🇲', code:'MCT',
      n:{ en:'Oman',           hi:'ओमान',           bn:'ওমান' },
      d:{ en:'Technical trades', hi:'टेक्निकल ट्रेड', bn:'টেকনিক্যাল ট্রেড' } },
    { id:'ru', fl:'🇷🇺', code:'MOW',
      n:{ en:'Russia',         hi:'रूस',            bn:'রাশিয়া' },
      d:{ en:'Factory & welding', hi:'फैक्ट्री और वेल्डिंग', bn:'ফ্যাক্টরি ও ওয়েল্ডিং' } },
    { id:'pl', fl:'🇵🇱', code:'WAW',
      n:{ en:'Poland',         hi:'पोलैंड',          bn:'পোল্যান্ড' },
      d:{ en:'Warehouse & production', hi:'वेयरहाउस और प्रोडक्शन', bn:'ওয়্যারহাউস ও প্রোডাকশন' } },
    { id:'ro', fl:'🇷🇴', code:'OTP',
      n:{ en:'Romania',        hi:'रोमानिया',        bn:'রোমানিয়া' },
      d:{ en:'Construction & hotel', hi:'कंस्ट्रक्शन और होटल', bn:'কনস্ট্রাকশন ও হোটেল' } },
    { id:'pt', fl:'🇵🇹', code:'LIS',
      n:{ en:'Portugal',       hi:'पुर्तगाल',        bn:'পর্তুগাল' },
      d:{ en:'Farm & restaurant', hi:'फ़ार्म और रेस्टोरेंट', bn:'ফার্ম ও রেস্তোরাঁ' } },
    { id:'ca', fl:'🇨🇦', code:'YYZ',
      n:{ en:'Canada',         hi:'कनाडा',          bn:'কানাডা' },
      d:{ en:'Skilled trades · LMIA', hi:'स्किल्ड ट्रेड · LMIA', bn:'স্কিলড ট্রেড · LMIA' } },
    { id:'us', fl:'🇺🇸', code:'JFK',
      n:{ en:'USA',            hi:'अमेरिका',         bn:'আমেরিকা' },
      d:{ en:'Seasonal work visa', hi:'सीज़नल वर्क वीज़ा', bn:'সিজনাল ওয়ার্ক ভিসা' } },
    { id:'sg', fl:'🇸🇬', code:'SIN',
      n:{ en:'Singapore',      hi:'सिंगापुर',        bn:'সিঙ্গাপুর' },
      d:{ en:'Marine & construction', hi:'मरीन और कंस्ट्रक्शन', bn:'মেরিন ও কনস্ট্রাকশন' } },
    { id:'my', fl:'🇲🇾', code:'KUL',
      n:{ en:'Malaysia',       hi:'मलेशिया',         bn:'মালয়েশিয়া' },
      d:{ en:'Factory & plantation', hi:'फैक्ट्री और प्लांटेशन', bn:'ফ্যাক্টরি ও প্ল্যান্টেশন' } },
    { id:'any', fl:'🌍', code:'ANY',
      n:{ en:'Any country',    hi:'कोई भी देश',      bn:'যে কোনও দেশ' },
      d:{ en:"We'll advise on call", hi:'फ़ोन पर बता देंगे', bn:'ফোনে বলে দেব' } }
  ],

  /* ---------- trades ---------- */
  jobs: [
    { id:'helper',     ic:'🧰', n:{ en:'Helper / Labour',        hi:'हेल्पर / लेबर',        bn:'হেল্পার / লেবার' },
      d:{ en:'No experience needed', hi:'बिना एक्सपीरियंस भी', bn:'এক্সপেরিয়েন্স ছাড়াও হয়' } },
    { id:'construct',  ic:'🏗️', n:{ en:'Construction worker',    hi:'कंस्ट्रक्शन वर्कर',     bn:'কনস্ট্রাকশন ওয়ার্কার' },
      d:{ en:'Most vacancies', hi:'सबसे ज़्यादा वैकेंसी', bn:'সবচেয়ে বেশি ভ্যাকান্সি' } },
    { id:'mason',      ic:'🧱', n:{ en:'Mason / Tiles',          hi:'मिस्त्री / टाइल्स',     bn:'রাজমিস্ত্রি / টাইলস' },
      d:{ en:'Experience needed', hi:'एक्सपीरियंस चाहिए', bn:'এক্সপেরিয়েন্স লাগবে' } },
    { id:'carpenter',  ic:'🪚', n:{ en:'Carpenter / Shuttering', hi:'कारपेंटर / शटरिंग',    bn:'কাঠমিস্ত্রি / শাটারিং' },
      d:{ en:'Experience needed', hi:'एक्सपीरियंस चाहिए', bn:'এক্সপেরিয়েন্স লাগবে' } },
    { id:'scaffold',   ic:'🧗', n:{ en:'Scaffolder',             hi:'स्कैफोल्डर',           bn:'স্ক্যাফোল্ডার' },
      d:{ en:'High pay, height work', hi:'अच्छी सैलरी, हाइट वर्क', bn:'ভালো মাইনে, উঁচুতে কাজ' } },
    { id:'welder',     ic:'🔥', n:{ en:'Welder / Fitter',        hi:'वेल्डर / फिटर',        bn:'ওয়েল্ডার / ফিটার' },
      d:{ en:'High pay', hi:'अच्छी सैलरी', bn:'ভালো মাইনে' } },
    { id:'electrician',ic:'💡', n:{ en:'Electrician',            hi:'इलेक्ट्रीशियन',        bn:'ইলেকট্রিশিয়ান' },
      d:{ en:'Certificate helps', hi:'सर्टिफिकेट हो तो बेहतर', bn:'সার্টিফিকেট থাকলে ভালো' } },
    { id:'plumber',    ic:'🔧', n:{ en:'Plumber',                hi:'प्लंबर',              bn:'প্লাম্বার' },
      d:{ en:'Experience needed', hi:'एक्सपीरियंस चाहिए', bn:'এক্সপেরিয়েন্স লাগবে' } },
    { id:'painter',    ic:'🎨', n:{ en:'Painter',                hi:'पेंटर',               bn:'পেইন্টার' },
      d:{ en:'Demand everywhere', hi:'हर देश में डिमांड', bn:'সব দেশেই চাহিদা' } },
    { id:'ac',         ic:'❄️', n:{ en:'AC / Refrigeration tech', hi:'AC / रेफ्रिजरेशन टेक', bn:'AC / রেফ্রিজারেশন টেক' },
      d:{ en:'High pay', hi:'अच्छी सैलरी', bn:'ভালো মাইনে' } },
    { id:'mechanic',   ic:'🛠️', n:{ en:'Mechanic / Auto tech',   hi:'मैकेनिक / ऑटो टेक',    bn:'মেকানিক / অটো টেক' },
      d:{ en:'Experience needed', hi:'एक्सपीरियंस चाहिए', bn:'এক্সপেরিয়েন্স লাগবে' } },
    { id:'driver',     ic:'🚗', n:{ en:'Driver (LMV / HMV)',     hi:'ड्राइवर (LMV / HMV)',  bn:'ড্রাইভার (LMV / HMV)' },
      d:{ en:'Licence required', hi:'लाइसेंस ज़रूरी', bn:'লাইসেন্স লাগবে' } },
    { id:'heavy',      ic:'🚧', n:{ en:'Heavy equipment operator', hi:'हेवी इक्विपमेंट ऑपरेटर', bn:'হেভি ইকুইপমেন্ট অপারেটর' },
      d:{ en:'Crane, JCB, excavator', hi:'क्रेन, JCB, एक्सकेवेटर', bn:'ক্রেন, JCB, এক্সকাভেটর' } },
    { id:'forklift',   ic:'🚜', n:{ en:'Forklift operator',      hi:'फोर्कलिफ्ट ऑपरेटर',    bn:'ফর্কলিফ্ট অপারেটর' },
      d:{ en:'Licence helps', hi:'लाइसेंस हो तो बेहतर', bn:'লাইসেন্স থাকলে ভালো' } },
    { id:'factory',    ic:'🏭', n:{ en:'Factory / Production',   hi:'फैक्ट्री / प्रोडक्शन',  bn:'ফ্যাক্টরি / প্রোডাকশন' },
      d:{ en:'No experience needed', hi:'बिना एक्सपीरियंस भी', bn:'এক্সপেরিয়েন্স ছাড়াও হয়' } },
    { id:'warehouse',  ic:'📦', n:{ en:'Warehouse / Packing',    hi:'वेयरहाउस / पैकिंग',    bn:'ওয়্যারহাউস / প্যাকিং' },
      d:{ en:'Mostly Europe', hi:'ज़्यादातर यूरोप', bn:'ইউরোপে বেশি' } },
    { id:'cnc',        ic:'⚙️', n:{ en:'CNC / Machine operator', hi:'CNC / मशीन ऑपरेटर',   bn:'CNC / মেশিন অপারেটর' },
      d:{ en:'Skilled post', hi:'स्किल्ड पोस्ट', bn:'স্কিলড পোস্ট' } },
    { id:'cleaner',    ic:'🧹', n:{ en:'Cleaner / Housekeeping', hi:'क्लीनर / हाउसकीपिंग',  bn:'ক্লিনার / হাউসকিপিং' },
      d:{ en:'No experience needed', hi:'बिना एक्सपीरियंस भी', bn:'এক্সপেরিয়েন্স ছাড়াও হয়' } },
    { id:'security',   ic:'🛡️', n:{ en:'Security guard',         hi:'सिक्योरिटी गार्ड',     bn:'সিকিউরিটি গার্ড' },
      d:{ en:'Height condition applies', hi:'हाइट की शर्त है', bn:'উচ্চতার শর্ত থাকে' } },
    { id:'hotel',      ic:'🏨', n:{ en:'Hotel staff / Waiter',   hi:'होटल स्टाफ / वेटर',    bn:'হোটেল স্টাফ / ওয়েটার' },
      d:{ en:'English helps', hi:'अंग्रेज़ी आए तो बेहतर', bn:'ইংরেজি জানলে ভালো' } },
    { id:'cook',       ic:'👨‍🍳', n:{ en:'Cook / Chef',            hi:'कुक / शेफ',           bn:'কুক / শেফ' },
      d:{ en:'Indian cooks in demand', hi:'इंडियन कुक की डिमांड', bn:'ইন্ডিয়ান কুকের চাহিদা' } },
    { id:'baker',      ic:'🥖', n:{ en:'Baker / Pastry',         hi:'बेकर / पेस्ट्री',      bn:'বেকার / পেস্ট্রি' },
      d:{ en:'Gulf & Europe', hi:'गल्फ और यूरोप', bn:'গাল্ফ ও ইউরোপ' } },
    { id:'farm',       ic:'🌾', n:{ en:'Farm / Agriculture',     hi:'फ़ार्म / खेती',        bn:'ফার্ম / কৃষি কাজ' },
      d:{ en:'Seasonal visa', hi:'सीज़नल वीज़ा', bn:'সিজনাল ভিসা' } },
    { id:'tailor',     ic:'🧵', n:{ en:'Tailor / Garments',      hi:'टेलर / गारमेंट्स',     bn:'দর্জি / গার্মেন্টস' },
      d:{ en:'Open to women too', hi:'महिलाओं के लिए भी', bn:'মেয়েদের জন্যও আছে' } },
    { id:'care',       ic:'🩺', n:{ en:'Caregiver / Nursing',    hi:'केयरगिवर / नर्सिंग',   bn:'কেয়ারগিভার / নার্সিং' },
      d:{ en:'Certificate required', hi:'सर्टिफिकेट ज़रूरी', bn:'সার্টিফিকেট লাগবে' } },
    { id:'salesman',   ic:'🛒', n:{ en:'Salesman / Storekeeper', hi:'सेल्समैन / स्टोरकीपर', bn:'সেলসম্যান / স্টোরকিপার' },
      d:{ en:'English required', hi:'अंग्रेज़ी ज़रूरी', bn:'ইংরেজি লাগবে' } },
    { id:'delivery',   ic:'🛵', n:{ en:'Delivery rider',         hi:'डिलीवरी राइडर',       bn:'ডেলিভারি রাইডার' },
      d:{ en:'Licence required', hi:'लाइसेंस ज़रूरी', bn:'লাইসেন্স লাগবে' } },
    { id:'other',      ic:'💼', n:{ en:'Other / Not sure',       hi:'अन्य / पता नहीं',      bn:'অন্য কাজ / জানি না' },
      d:{ en:"We'll guide you", hi:'हम बता देंगे', bn:'আমরা বলে দেব' } }
  ]
};
